{{- $count := .Values.nsNumber | default 50 | toString | atoi }}
{{- range $i, $ := until $count }}
---
kind: Namespace
apiVersion: v1
metadata:
  name: managed-ns-{{ add $i 1 }}
  labels:
    argocd.argoproj.io/managed-by: argocd-ns
    pod-security.kubernetes.io/enforce-version: v1.29
    pod-security.kubernetes.io/warn: restricted
    openshift.io/cluster-monitoring: 'true'
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn-version: latest
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit-version: latest
spec:
  finalizers:
    - kubernetes
{{- end }}